import localFont from 'next/font/local';
import { Roboto } from 'next/font/google';
import './globals.css';
/* components */
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const notoSans = localFont({
  src: [
    {
      path: './fonts/NotoSans-ExtraLight.ttf',
      weight: '200', // Extra Light
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-Light.ttf',
      weight: '300', // Light
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-Regular.ttf',
      weight: '400', // Regular
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-Medium.ttf',
      weight: '500', // Medium
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-SemiBold.ttf',
      weight: '600', // Semi Bold
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-Bold.ttf',
      weight: '700', // Bold
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-ExtraBold.ttf',
      weight: '800', // Extra Bold
      style: 'normal',
    },
    {
      path: './fonts/NotoSans-Black.ttf',
      weight: '900', // Black
      style: 'normal',
    },
  ],
  variable: '--font-noto-sans',
});

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden max-w-screen antialiased`}>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
